name: flutter_api_rest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  dio: ^5.4.2+1
  logger: ^2.2.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.7
  image_picker: ^1.0.7
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
  - assets/hoguera.svg
